controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
registration.register:
    path: /register
    controller: App\Controller\RegistrationController::register
lucky.number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
app_logout:
    path: /logout
movie.dashboard:
    path: /movies/dashboard
    controller: App\Controller\MovieController::index

