# config/packages/doctrine.yaml

doctrine:
  dbal:
    # configure these for your database server
    driver: 'pdo_mysql'
    server_version: '10.5.8'
    host: '127.0.0.1'
    port: 3306
    dbname: 'movie'
    user: 'nasrin'
    password: 'nasrin'
    charset: utf8mb4

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        #type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
  # Other ORM configurations...
